import sys
sys.path.insert(0, '../../hibuilder/')

from hibuilder import HiBuilder

env = Environment()

b = HiBuilder("poolserver_test")

hicore_path = "../../../"
hiaux_path = "../../../"

b.addPath(hicore_path)
b.addPath(hiaux_path)
b.addPath("../")
b.addPath("./")

b.connectLib("../../threads/")
b.connectLib("../")

b.addCppGlob("*.cpp")

b.buildProgram(Program)
