_CCFLAGS = '-c -Wall '

_LINKFLAGS = '-g -v '

_CXX = ' clang++'# -Wc++11-extensions'

Program('threadpool_test', 
['../../threadpool/threadpool.cpp',
'../hpoolserver.cpp',
'hpoolserver_main.cpp',
'../../threadpool/tasklauncher.cpp',
'../../threadpool/locks.cpp'], LIBS=['pthread'], 
LIBPATH='.', CCFLAGS=_CCFLAGS, LINKFLAGS=_LINKFLAGS, CXX=_CXX)
