import sys
import os
import glob
import subprocess

platform = sys.platform
print "PLATFORM:"+platform

_CCFLAGS = '-v'
_CXX = ''
_LINKFLAGS = '-lprotobuf -lprotobuf-lite -lc++ -lc++abi -lpthread -v'

#LINUX
if platform[:5]=="linux":
	_CCFLAGS = '-std=c++11 -stdlib=libstdc++'
        _CXX = 'clang++'    
        _LINKFLAGS = ''
#MACOSX
if platform=="darwin":
	_CCFLAGS = '-std=c++11 -stdlib=libc++ -Wno-c++98-compat'	
	_CXX = 'clang++'

env = Environment()
Program('mapr_test', 
['mapr_test.cpp',
'../core/mapreduce.cpp',
'../core/MRInterResult.cpp',
'../core/MRBatchDispatcher.cpp',
'../core/ReduceDispatcher.cpp',
'../../threadpool/threadpool.cpp',
'../core/FileCartulary.cpp',
'invertline.pb.cc'], LIBS=[], LIBPATH='.', CCFLAGS=_CCFLAGS, CXX=_CXX, LINKFLAGS=_LINKFLAGS)
