env = Environment(CCFLAGS='-std=gnu++11 ')
Program('hstringid',
['../hrpc/hcomm/src/hcomm.cpp',
'../hrpc/hcomm/src/hcomms.cpp',
'../hrpc/hcomm/src/objrepr.cpp',
'../hrpc/hcomm/src/common.cpp', 
'../hrpc/hcomm/src/sendchannel.cpp', 
'hstringid_main.cpp'], LIBS=['bson', 'mongoc', 'pthread'], LIBPATH='.')
