import sys
sys.path.insert(0, '../../hibuilder/')

from hibuilder import HiBuilder

env = Environment()

b = HiBuilder("network_tests", "clang++")

hicore_path = "../../../"
hiaux_path = "../../../"

b.addPath(hicore_path)
b.addPath(hiaux_path)
b.addPath("../")
b.addPath("./")

b.connectLib("../")

b.connectLib("../../threads/")

b.addPath(hicore_path+"thirdparty/http-parser/")
b.connectLib(hicore_path+"thirdparty/http-parser/")

b.addCCFlags(["-g3"])
#b.addLinkFlags(["-g"])

b.addCppGlob("*.cpp")

b.build(Program)
