import sys
import os
import glob
import subprocess

platform = sys.platform
print "PLATFORM:"+platform

_CCFLAGS = '-g -I/usr/local/include/c++/v1 -I/usr/local/include'
_CXX = ''
_LINKFLAGS = '-g '



#LINUX
if platform[:5]=="linux":
	_CCFLAGS += ' -std=c++11 -stdlib=libstdc++'
	_CXX += ' clang++'
	_LINKFLAGS += ' -lprotobuf -lpthread'

#FREEBSD9
if platform[:7]=="freebsd":
	_CCFLAGS = '-g -std=c++11 -stdlib=libstdc++ -I/usr/local/include -I/usr/local/include/c++/v1'
	_CXX = 'clang++'
	_LINKFLAGS = ' -v -lpthread -lprotobuf  -lc++ -L../protobuf-2.5.0/src/.libs -Wl,-rpath=../protobuf-2.5.0/src/.libs'

#MACOSX
if platform=="darwin":
#	_CCFLAGS += ' -std=c++11 -stdlib=libc++ -Wno-c++98-compat'
#	_CXX += ' clang++'
#	_LINKFLAGS += ' -lprotobuf -lprotobuf-lite -lc++ -lc++abi -lpthread'
	_CCFLAGS += ''
	_CXX += ' clang++ -Wc++11-extensions'
	_LINKFLAGS += ' -lprotobuf -lprotobuf-lite -lpthread'


env = Environment()
Program('mapr_unit', 
['mapr_unit.cpp',
'../example_invindex/mapr_test.cpp',
'../example_invindex/invertline.pb.cc',
'../core/mapreduce.cpp',
'../core/MRInterResult.cpp',
'../core/InterResultReader.cpp',
'../core/MRInterMerger.cpp',
'../core/MRBatchDispatcher.cpp',
'../core/MRNodeDispatcher.cpp',
'../../threadpool/threadpool.cpp',
'../../threadpool/tasklauncher.cpp',
'../core/FileCartulary.cpp'], LIBS=[], LIBPATH='.', CCFLAGS=_CCFLAGS, CXX=_CXX, LINKFLAGS=_LINKFLAGS)
