/*
Generated by vardist stub generator. Don't change.
Server stub for data_t
*/

#pragma once
#include "data.h"


class data_tskel_t : public skel_t
{
	data_t *obj;

	char bf[255]; 
 	int bfi; 
 	float bff;
	public: 

	data_tskel_t(data_t *o) { obj = o; }

	virtual char *call(int socket, char *command) 
	{ 
		//remote function (#remote) 
		if (!strcmp(command, "request\n")) 
		{ 
			char* ret = obj->request();
			strcpy(bf, ret);
			strcat(bf, "\n");
			send(socket, bf, 255, 0); 

			
		} 
		//End remote function 

		vector<pair<char,int> >request_ret;
		int request_ncall;
		sem_t request_sem;


	} 

 
 };
