/*
Generated by vardist stub generator. Don't change.
Client stub for data_t
*/

#pragma once
#include "data.h"


class data_tstub_t: public stub_t
{
	char bf[255];
	int bfi; 
 	float bff;
 public:  
	int socket; 

		void close() 
		{
		strcpy(bf,"ifs stop\n"); 
		send(socket, bf, 255, 0);  
		}

		data_tstub_t(hcomm_t *c, char *name) 
 		{
 			c->open_ifs<data_tstub_t>(this, name, NULL); 
 		} 

		//remote function (#remote) 
		char *request(char* a) 
		{ 
		log("CALLL");
			send(socket, "request\n", 255, 0);
			strcpy(bf, a);
			strcat(bf, "\n");
			send(socket, bf, 255, 0); 

			char* ret = new char [255];
			recv(socket,ret, 255, 0); 

			return ret;

		} 
		//End remote function 

		vector<pair<char,int> >request_ret;
		int request_ncall;
		sem_t request_sem;

		int request_call(char* a)
		{
			pair<char,int> aret;
			aret.second = request_ncall;
			request_ncall++;
			sem_wait(&request_sem);
			request_ret.push_back(aret);
			sem_post(&request_sem);
			return aret.second;
		}

 
 };
