import installer

env = Environment()

meroving = StaticLibrary('meroving', 
['src/hcomm.cpp',
 'src/hcomms.cpp',
'src/common.cpp',
'src/sendchannel.cpp',
'src/objrepr.cpp',
'src/hlog.cpp'])


# create the installer
install = installer.Installer( env )


# adds a library to the installer
#lib = env.Library( your_library_options )
install.AddLibrary( meroving )

# adds headers to the installer
install.AddHeaders( "include", "*.h", "meroving")