env = Environment(CCFLAGS='-std=gnu++11 ')
Program('hdivider_test', 
['../src/hdivider_watcher.cpp', 
'../src/hdivider_worker.cpp',
'hdivider_test.cpp',
'one_worker_test.cpp',
'concurrent_read_test.cpp',
'concurrent_write_test.cpp',
'one_fault_test.cpp',
'main.cpp'], LIBS=['bson', 'mongoc'], LIBPATH='.')
