env = Environment()
Program('mapr_test', 
['mapr_test.cpp',
'../core/mapreduce.cpp',
'../core/MRBatchDispatcher.cpp',
'../core/ReduceDispatcher.cpp',
'../../threadpool/threadpool.cpp',
'../core/FileCartulary.cpp'], LIBS=['pthread'], LIBPATH='.', CCFLAGS='-std=c++11 -stdlib=libc++ -Wno-c++98-compat -g', CXX='clang++', 
LINKFLAGS='-lc++')
